### ISSUE TITLE
Validación contraseña de usuario nuevo

### ISSUE THREAD

**Issue by thalia1218** [DesignerSoftware/DesignerKIO_4_web#2]
La expresión regular dice que la contraseña debe tener:

- Al menos una minúscula
- Al menos una mayúscula
- Al menos un número
- Al menos un carácter especial (  **@#$%*.-_+~/;,()!**  )
- Longitud mínima de 8 caracteres
- Longitud máxima de 16 caracteres

Pero en este momento está aceptando contraseñas sin caracteres especiales, lo cual no es correcto.

**Comment by EdwinHasta** [comment]
Se revisó la forma en la que se registra la expresión regular, siendo necesario utilizar comillas dobles y doble backslash, en lugar de utilizar comilla sencilla y backslash.
